name: 'setup-roxctl'
description: 'Download and install roxctl cli'
author: 'Ram Gopinathan'
branding:
  icon: circle
  color: red
inputs:
  version:
    description: "Version of roxctl that needs to be installed"
    required: false
    default: "latest"
  output-path:
    description: "Path to download the roxctl cli"
    required: false
    default: ""
outputs:
  binaryPath:
    description: "Directory where the roxctl cli was installed"
runs:
  using: 'node16'
  main: 'dist/index.js'