name: example
on:
  workflow_dispatch:
    inputs:
      version:
        description: Version of roxctl to setup
        type: string
        default: "latest"
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: setup roxctl
        id: setup-roxctl
        uses: rprakashg-redhat/setup-roxctl@main
        with:
          version: ${{ inputs.version }}
      - run: |
          echo "${{ steps.setup-roxctl.outputs.destination }}"
      - name: verify
        run: |
          ./roxctl version
          ./roxctl help
        env:
          PATH: "${PATH}:${{ steps.setup-roxctl.outputs.destination }}"